version: '3'
services:
  planet-dump-ng:
    image: quay.io/geotrellis/planet-dump-ng:latest
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    build:
      context: planet-dump-ng
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
  osm2orc:
    image: quay.io/geotrellis/osm2orc:latest
    build:
      context: osm2orc
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
  db:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    volumes:
      - ./data/:/tmp/data/
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "osm"
      POSTGRES_USER: "osm"
      POSTGRES_DB: "openstreetmap"
  osm-pgsample:
    image: quay.io/geotrellis/osm-pgsample:latest
    volumes:
      - ./data/:/tmp/data/
    links:
      - "db:database"
    build:
      context: osm-pgsample
      dockerfile: Dockerfile
    environment:
      PGHOST: "database"
      PGPORT: "5432"
      PGUSER: "osm"
      PGPASSWORD: "osm"
      PGDATABASE: "openstreetmap"
    stdin_open: true
    tty: true

