#!/bin/sh
set -e

usage() {
  echo "Usage: $0 [-i <string> (input path)] [-s <string> (scratch directory)] [-o <string> (output path)]" 1>&2
  exit 1
}

while getopts ":i:s:o:" x; do
    case "${x}" in
        i)
            i=${OPTARG}
            echo "I!"
            ;;
        s)
            s=${OPTARG}
            ;;
        o)
            o=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${i}" ] || [ -z "${s}" ] || [ -z "${o}" ]; then
    usage
fi

pgdump2pbf() {
  mkdir -p $2/working
  cd $2/working
  planet-dump-ng -f $1 --history-pbf $2/osm-dump.osh.pbf
}

# pgdump to pbf
pgdump2pbf $i $s

# pbf to orc
osm2orc $s/osm-dump.osh.pbf $o
